---
title: "HW 06: Data Importing and Wrangling 1"
subtitle: "Graphical Analysis of Biological Data"
output:
  pdf_document: default
  html_document:
    df_print: paged
    toc: yes
#    latex_engine: lualatex
urlcolor: blue
---

```{r include=FALSE}
knitr::opts_chunk$set(include = TRUE, eval = TRUE)
```

**This assignment is long. Allow yourself plenty of time.**

By the end of this assignment, you should be able to achieve the following tasks in R:

- use R notebooks and R markdown;
- insert, write, and evaluate code chucks; 
- import data from a variety of source formats;
- make untidy data tidy;
- arrange, filter, and select data;
- use pipes; and
- confidently stage, commit, and push with Git.

*These achievements belong to Learning Outcomes 2, 3, 5, 6.*

Click on any blue text to visit the external website.

**Note:** If you contact me for help or (better yet) open an issue in the [public discussion forum,](https://github.com/SEMO-GABD/public_discussion) please include the code that is not working and also tell me what you have tried.

## Preparation

- Create an `hw06` folder inside the same folder as your project file.

    You will store all your data files that you use for this course in this folder. That allows everyone in class to have a common path to the data.

- Open your `.Rproj` project file in RStudio.

- Install the `nycflights13` package. You will need it to complete this assignment.

- Download this [R Notebook file](https://raw.githubusercontent.com/SEMO-GABD/semo-gabd.github.io/master/assignments/hw06/worksheet_hw06.Rmd). Right-click to save the file as `<lastname>_hw06.Rmd` inside the "hw06" folder.

## Assignment

Read the following sections. As you read the assigned sections, insert a code chunk in your notebook and recreate *every* example in that section, except for those I tell you in the notebook to skip. *Type the code!*  In the next assignment, you will have to type the code from scratch so typing the code will help you remember it better. The point here is *learn* how to do this! 

- Answer the questions in each section, except where I tell you to skip them. You will have to enter code chunks to answer the quwstions and also to write text outside of the code chunks. In other words, you will take advantage of R Notebook features.

- For each code chunk you add, write a brief description of what that chunk does. That includes examples and questions. Writing these descriptions will help you learn and understand the code.

- Some answers will require you to run code and enter text. Other questions will require only one or the other. The questions should give you the context you need.

- **Stage and commit regularly!**  A good habit would be to stage and commit after you complete each section. You should also push each time but at least push your completed notebook to your remote repo.

**You will apply the skills you learn from this assignment in the next and subsequent assignments. Learn them well!**