---
title: "Assignment Schedule"
output: github_document
---

Here is the schedule of assignments, with links to appear after assignments are released. Your completed assignments are due by 23:55 of the scheduled due date.

Follow links in the Reading column for background information. The Reading webpage will have a link to a PDF file with the same content.

Assignments are available in HTML and PDF formats. They have the same content so you only need to complete one. Resources has links to places necessary to complete an assignment or to supporting information. The readings listed in the Notes and Assignments pages are the officially assigned readings that you *must* completed. 

**Note:** Click on blue links in PDF files to visit those web sites.

**Warning:** I am still changing this schedule! Order and content is highly susceptible to change.

| Reading   | Assignment     | Due&nbsp;(23:55) | Resources |
|:----------|:---------------|:---------|:----------|
| [01 Install software;<br/> Markdown](../notes/notes01.html) | [HTML](hw01/hw01.html) / [PDF](hw01/hw01.pdf) | 19 Dec (W) | [Markdown](https://commonmark.org/help/tutorial/) tutorial |
| 02 Learn R! <br/> Assignment Intro (Pt. 0) | [HTML](hw02/00_intro.html) / [PDF](hw02/00_intro.pdf) |  21 Dec (F)  | Read this first!  | 
| 02 Basics (Pt 1) | [HTML](hw02/01_intro_to_basics.html) / [PDF](hw02/01_intro_to_basics.pdf) |  21 Dec (F)  | Do all six parts!  | 
| 02 Vectors (Pt. 2) | [HTML](hw02/02_vectors.html) / [PDF](hw02/02_vetors.pdf) |  21 Dec (F)  |  |
| 02 Matrices (Pt. 3) | [HTML](hw02/03_matrices.html) / [PDF](hw02/03_matrices.pdf) |  21 Dec (F)  |  | 
| 02 Factors (Pt. 4) | [HTML](hw02/04_factors.html) / [PDF](hw02/04_factors.pdf) |  21 Dec (F)  |  | 
| 02 Data Frames (Pt. 5) | [HTML](hw02/05_data_frames.html) / [PDF](hw02/05_data_frames.pdf) |  21 Dec (F)  |  | 
| 02 Lists (Pt. 6) | [HTML](hw02/06_lists.html) / [PDF](hw02/04_lists.pdf) |  21 Dec (F)  | [R4ds Chapter 1](https://r4ds.had.co.nz/introduction.html)<br/> [R4ds Chapter 2](http://r4ds.had.co.nz/communicate-intro.html)<br/> [R4ds Chapter 4](https://r4ds.had.co.nz/workflow-basics.html)<br/> [R4ds Chapter 6](https://r4ds.had.co.nz/workflow-scripts.html)<br/> [R4ds Chapter 8](https://r4ds.had.co.nz/workflow-projects.html) | 
| [03 R Studio<br/>R Markdown<br/>Git and GitHub](../notes/notes03.html) | [HTML](hw03/hw03.html) / [PDF](hw03/hw03.pdf) |  23 Dec (Su) | [R4ds Chapter 4](http://r4ds.had.co.nz/workflow-basics.html) (review)<br/>[R4ds Chapter 26](http://r4ds.had.co.nz/communicate-intro.html)<br/>[R4ds Chapter 27](http://r4ds.had.co.nz/r-markdown.html)<br/>[R4ds Chapter 29](http://r4ds.had.co.nz/r-markdown-formats.html), sect 1-3<br/> [R Markdown tutorial](https://rmarkdown.rstudio.com/lesson-1.html)<br/> [GitHub Tutorial](https://guides.github.com/activities/hello-world/) |
| [04 Data Visualization](../notes/notes04.html) | [HTML](hw04/hw04.html) / [PDF](hw04/hw04.pdf) |  26 Dec (W) | [R4ds Chapter 3](https://r4ds.had.co.nz/data-visualisation.html) |
| [05 Importing and Wrangling I](../notes/notes05.html) | [HTML](hw05/hw05.html) / [PDF](hw05/hw05.pdf) |  28 Dec (F) | [R4ds Chapter 10](https://r4ds.had.co.nz/tibbles.html), sections 1-3.<br/> [R4ds Chapter 11](https://r4ds.had.co.nz/data-import.html), sections 1-2, 5<br/> [R4ds Chapter 18](https://r4ds.had.co.nz/pipes.html), sections 1-3<br/> [R4ds Chapter 12](https://r4ds.had.co.nz/tidy-data.html) sections 1-3, 7<br/> [R4ds Chapter 5](https://r4ds.had.co.nz/transform.html) sections 1-4<br/> [Data Import](https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf) cheatsheet<br/>[Data Transformation](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf) cheatsheet |
| 06  | HTML / PDF |  30 Dec (Su) |  |
| 07  | HTML / PDF |  02 Jan (W) |  |
| 08  | HTML / PDF |  04 Jan (F) |  |
| 09  | HTML / PDF |  06 Jan (Su) |  |
| 10  | HTML / PDF | 09 Jan (W) |  |
| 11 Maps | HTML / PDF | 11 Jan (F) | |


## Logistics

Here is the general flow that will happen for the assignments.

1.  When a assignments are released, I will post a GitHub Issue in the [Internal Discussion](https://github.com/semo-gabd/internal_discussion) repo, tagging the students (you should get an email notification, too, unless you've somehow disabled this, are not `Watch`ing the Internal Discussion repo, or did not inform me of your GitHub username).
2.  Create a new homework folder called `hw##` inside the folder on your computer that you created for this class. Replace the `##` with the assignment number, e.g., `hw01`, `hw02`, etc. **Use a separate folder for each assignment.** By the end of the course, you should have folders labeled `hw01` through `hw11`.
3.  Download any `.Rmd` or other files associated with the assignment and place them in your new homework folder.
4.  Complete the assignment. Push your edits to your GitHub repository often while you work.
5. After you have pushed the final version you want graded, go to the [GABD Students](https://github.com/gabd-students) GitHub page and open an issue in *your* repository. Add the `@instructor` tag and the Git SHA number for the version you want graded. 
6. I will grade the version of your completed assignment that matches the SHA. I will add any comments about your assignment as an issue in your GitHub repository, and post the grade in Moodle.


## Evaluation

Components of each assignment will be graded on a 3-point scale. Here is the general rubric *(also consult any specific guidance given in the relevant assignment itself).*

A few assignments (exact number still to be determined) will have extra work for graduate and honors contract students that *must* be completed. Other students may attempt the extra work but I will not include your attempt in your grade.

Topic| Excellent: 3 | Satisfactory: 2 | Needs work: 1 |
|----| ------ |-------| -----|
|Coding style| Student has gone beyond what was expected and required, [coding manual](https://style.tidyverse.org) is followed, code is well commented | Coding style lacks refinement and has some errors, but code is readable and has some comments | Many errors in coding style, little attention paid to making the code human readable|
|Coding strategy| Complicated problem broken down into sub-problems that are individually much simpler. Code is efficient, correct, and minimal. Code uses appropriate data structure (list, data frame, vector/matrix/array). Code checks for common errors  | Code is correct, but could be edited down to leaner code. Some "hacking" instead of using suitable data structure. Some checks for errors. |   Code tackles complicated problem in one big chunk. Code is repetitive and could easily be functionalized. No anticipation of errors. |
|Presentation: graphs | Graph(s) carefully tuned for desired purpose. One graph illustrates one point | Graph(s) well chosen, but with a few minor problems: inappropriate aspect ratios, poor labels. | Graph(s) poorly chosen to support questions. |
|Presentation: tables | Table(s) carefully constructed to make it easy to perform important comparisons. Careful styling highlights important features. | Table(s) generally appropriate but possibly some minor formatting deficiencies.| Table(s) with too many, or inconsistent, decimal places. Table(s) not appropriate for questions and findings. Major display problems.|
|Achievement, mastery, cleverness, creativity|Student has gone beyond what was expected and required, e.g., extraordinary effort, additional tools not addressed by this course, unusually sophisticated application of tools from course.|Tools and techniques from the course are applied very competently and, perhaps,somewhat creatively. Chosen task was acceptable, but fairly conservative in ambition.|Student does not display the expected level of mastery of the tools and techniques in this course. Chosen task was too limited in scope.|
|Ease of access for instructor, compliance with course conventions for submitted work|Access as easy as possible, code runs! | Satisfactory | Not an earnest effort to reduce friction and comply with conventions  and/or code does not run|

**Warning:** I will run your code on the original data. You may be tempted to modify the data file in Excel or other editor to "ease" importing and wrangling. That defeats the purpose of this course and a strength of R. If your code does not work on the original data, then I will consider your code as non-working.

## Grades

Grades are mapped as follows:

| Grade | Percentage |
|------:|-----------:|
| 3.0 | 100% |
| 2.5 | 90% |
| 2.0 | 80% | 
| 1.5 | 70% |
| 1.0 | 60% | 
| 0.0 | 0% | 

Intermediate points are allowed, and follow a linear scale in between each point, so that the full mapping is depicted in the following chart:

```{r, echo=FALSE, fig.width=5, fig.height=3, fig.align='center'}
library(ggplot2)
df <- data.frame(x = c(0,1,2,3), y = c(0, 60, 80, 100))
ggplot(df) +
  geom_point(aes(x = x, y = y)) +
  geom_line(aes(x = x, y = y)) +
    theme_bw() +
    scale_y_continuous("Percent grade", limits=c(0,100), breaks=0:5*20) +
    xlab("Integer grade")
```

Undergraduates must have an average grade of 60% or better to pass this course. Graduate students must have an average grade of 70% or better to pass. 

