---
title: "Introduction to R"
subtitle: Graphical Analysis of Biological Data
output:
  pdf_document:
    latex_engine: lualatex
  html_document:
    df_print: paged
    toc: yes
urlcolor: blue
linkcolor: blue
editor_options:
  chunk_output_type: inline
mainfont: Linux Libertine O
---

This web page is available as a [PDF file](./notes02.pdf)

## Read

As you read these chapters, you should type some of the examples into your console for practice.

[R4ds: Chapter 4](https://r4ds.had.co.nz/workflow-basics.html) covers material related to the assignment. A few things to note:

* 4.1: Mac users should use the `option` key instead of the `Alt` key. For example, to type the `<-` assignment operator, Mac users will hold down the `option` key and then press the `-` key (the minus sign). PC users will hold down the `Alt` key and then press the `-` key (the minus sign). Remember this throughout the course: the option and alt keys are for Mac and PC computers, respectively. 

* 4.2: Pay careful attention to object names. Like the authors of the text, `i_use_snake_case` with lowercase letters and underscores for spacing. *Never* use actual spaces. Numbers are okay, too. 

* 4.2: Case matters. `A` and `a` are two different things (objects) in R.

* 4.4: Try to answer questions 1 and 3. Question 2 might not make sense until after we finish Chapter 3. You do not have to turn in answers for these questions but you should do them to learn an important point (question 1) and an important feature of RStudio (question 3).

[R4ds: Chapter 6](https://r4ds.had.co.nz/workflow-scripts.html) where you can practice some of your new-found R skills in RStudio. Practice some of the code from [Chapter 4](https://r4ds.had.co.nz/workflow-basics.html) in RStudio. Find some other code online and practice with it. I stress again that typing code again and again is the best way to learn it.

* 6.1: Do remember to *not* include `install.packages()` commands in your scripts. Use the command in the console window or from the `Tools` menu. Otherwise, RStudio will try install the package(s) every time you run your script.  You'll probably forget once or twice but you'll soon remember after you realize you are wasting time.

Remember in [Notes 01](./notes01.html), I said to "save that which is real?" [R4ds: Chapter 8](https://r4ds.had.co.nz/workflow-projects.html) ties that philosophy to R Projects and organization of your R scripts. Study this chapter carefully and follow it closely.

## Assignment

Homework 02 has six parts. The first three parts have one due date and the last three parts follow on the next due date. Please see the [assignment schedule](../assignments/) for due dates.  

On to [the assignment!](../assignments/hw02/hw02.html)
